### ISSUE TITLE
Excited!!!!!

### ISSUE THREAD

**Issue by onlinejudge95** [thisisashukla/cv-blog#1]
Looking forward to the URL :)

**Comment by thisisashukla** [comment]
Hi @onlinejudge95 thanks for your motivating comment. How did you find this repo though? I have not even added any topics to the repo. The contents will be from https://github.com/thisisashukla/cv-tutorial. Have a look at that repo until this is up.

**Comment by onlinejudge95** [comment]
@thisisashukla I have been following you on Github, your activities show up in my feed. BDW thanks for the repo.

**Comment by thisisashukla** [comment]
@onlinejudge95 nice to know that. i'll try to put up worthy content on the blog.
